night_light = { enabled = true, latitude = 53.287405, longitude = -6.123309, temperature = 5500 }

vibrance_configs = [
  { window_class = "firefox", window_title = "", strength = 100 },
  { window_class = "mplayer2", window_title = "Video Player", strength = 100 },
]

hot_reload = true

# Manual
# night_light = { enabled = true, start_time = "20:00", end_time = "20:30", temperature = 3500 }

# vibrance_configs = [
#   { window_class = "firefox", window_title = "", strength = 100 },
#   { window_class = "mplayer2", window_title = "Video Player", strength = 100 },
# ]

# hot_reload = true